###CODE FOR CALCULATING KENDALL TAU VALUES FOR THE EARLY WARNING INDICATORS#####
# Kendall tau for both of the leading indicators AR1 and SD are calculted for shallow-lake model
# As all the codes for each models or each indicator are same. Here we used the shallow-lake model as an example and guides how one can 
# reproduce the figures for other models also.

library(ggplot2)
library(reshape2)
library(vroom)
library(foreach)
library(doParallel)
###Function generated by using the "earlywarnings" package (Dakos. et.al, 2012)
## change winsize and bandwidth for different window sizes and bandwidths.
K_tauf <- function(timeseries,indicator = c("AR(1)", "SD"),winsize = 50,bandwidth = 10)
  
{
  
  timeseries <- data.matrix(timeseries)
  if (dim(timeseries)[2] == 1) {
    Y = timeseries
    timeindex = 1:dim(timeseries)[1]
  } else if (dim(timeseries)[2] == 2) {
    Y <- timeseries[, 2]
    timeindex <- timeseries[, 1]
  } else {
    warning("not right format of timeseries input")
  }
  
  # Gaussian detrending
  
  if (is.null(bandwidth)) {
    bw <- round(bw.nrd0(timeindex))
  } else {
    bw <- round(length(Y) * bandwidth)/100
  }
  smYY <- ksmooth(timeindex, Y, kernel = c("normal"), bandwidth = bw, range.x = range(timeindex), 
                  n.points = length(timeindex))
  nsmY <- Y - smYY$y
  
  
  
  # Rearrange data for indicator calculation
  mw <- round(length(Y) * winsize)/100
  omw <- length(nsmY) - mw + 1
  low <- 6
  high <- omw
  nMR <- matrix(data = NA, nrow = mw, ncol = omw)
  for (i in 1:omw) {
    Ytw <- nsmY[i:(i + mw - 1)]
    nMR[, i] <- Ytw
  }
  
  
  # Estimate indicator
  indicator = match.arg(indicator)
  if (indicator == "AR(1)") {
    indic <- apply(nMR, 2, function(x) {
      nAR <- ar.ols(x, aic = FALSE, order.max = 1, dmean = FALSE, intercept = FALSE)
      nAR$ar
    })
  }
  else if (indicator == "SD") {
    indic <- apply(nMR, 2, sd)
  }
  
  # Calculate trend statistics
  timevec <- seq(1, length(indic))
  Kt <- cor.test(timevec, indic, alternative = c("two.sided"), method = c("kendall"), 
                 conf.level = 0.95)
  K_tau <- Kt$estimate
  K_taup <- Kt$p.value
  
  return(K_tau)
}

## Finding Kendall tau values for each indicators corresponding to Shallow-lake model #####

## indicators
in1="SD"
in2="AR(1)"

# Kendall tau calculation for AR1 corresponding to Macrophyte population

######################### for q=0.0 ###################################
dat=vroom("lake150_M_ews_q0.0_k0.0.csv") ## Load the 150 replicas of pre-transition time series data generated for computing EWS strength for 
#the macrophyte population in the shallow-lake model (for q = 0.0). Ensure that this file is saved in the current working directory before proceeding.

cl<- makeCluster(10) # make cluster for parallel computing
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X # gives 150 tau values for AR1 
stopCluster(cl)
tau1=c(X) # vector containing 150 tau values

#############################for q=0.225 #############################################
dat=vroom("lake150_M_ews_q0.225_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau2=c(X)

################################ for q=0.45 ##########################################
dat=vroom("lake150_M_ews_q0.45_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau3=c(X)

################################## for q=0.675 ###########################################
dat=vroom("lake150_M_ews_q0.675_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau4=c(X)

################################ for q=0.9 ################################################
dat=vroom("lake150_M_ews_q0.9_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau5=c(X)

## Combine the tau values we get for each species response correlation (q) value
tau=cbind(tau1,tau2,tau3,tau4,tau5)
colnames(tau)=c("0.0","0.225","0.45","0.675","0.9")
tau=data.frame(tau)
write.csv(tau,"lake150_M_ktau_AR1_k0.0.csv") ## saved the tau values for AR1 as csv file and will be use to box plot for each q



############### Kendall tau calculation for SD corresponding to Macrophyte population################

##################### q=0.0 ##################################
dat=vroom("lake150_M_ews_q0.0_k0.0.csv") ## read the 150 replicas of pre-transition time series data generated to calculate EWS strength

cl<- makeCluster(10) # make cluster for parallel computing
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X # gives 150 tau values for SD
stopCluster(cl)
tau1=c(X) # vector containing 150 tau values
############################for q=0.225 ##############################################
dat=vroom("lake150_M_ews_q0.225_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau2=c(X)
################################for q=0.45##########################################
dat=vroom("lake150_M_ews_q0.45_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau3=c(X)

###################################for q=0.675##########################################
dat=vroom("lake150_M_ews_q0.675_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau4=c(X)

####################################for q=0.9############################################
dat=vroom("lake150_M_ews_q0.9_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau5=c(X)

## Combine the tau values we get for each species response correlation (q) value
tau=cbind(tau1,tau2,tau3,tau4,tau5)
colnames(tau)=c("0.0","0.225","0.45","0.675","0.9")
tau=data.frame(tau)
write.csv(tau,"lake150_M_ktau_SD_k0.0.csv") ## saved the tau values for SD as csv file and will be use to box plot for each q


##### In similar way using this code one can easily generate the Kendall's tau values for Algae (species 2) population.

######################### for q=0.0 ###################################
dat=vroom("lake150_A_ews_q0.0_k0.0.csv") ## read the 150 replicas of pre-transition time series data generated to calculate EWS
## for Algae population of shallow-lake model. This file must be saved in the current working directory. 

cl<- makeCluster(10) # make cluster for parallel computing
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X # gives 150 tau values for AR1 
stopCluster(cl)
tau1=c(X) # vector containing 150 tau values

#############################for q=0.225 #############################################
dat=vroom("lake150_A_ews_q0.225_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau2=c(X)

################################ for q=0.45 ##########################################
dat=vroom("lake150_A_ews_q0.45_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau3=c(X)

################################## for q=0.675 ###########################################
dat=vroom("lake150_A_ews_q0.675_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau4=c(X)

################################ for q=0.9 ################################################
dat=vroom("lake150_A_ews_q0.9_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in2)
}
X
stopCluster(cl)
tau5=c(X)

## Combine the tau values we get for each species response correlation (q) value
tau=cbind(tau1,tau2,tau3,tau4,tau5)
colnames(tau)=c("0.0","0.225","0.45","0.675","0.9")
tau=data.frame(tau)
write.csv(tau,"lake150_A_ktau_AR1_k0.0.csv") ## saved the tau values for AR1 as csv file and will be use to box plot for each q



############### Kendall tau calculation for SD corresponding to Algae population################

##################### q=0.0 ##################################
dat=vroom("lake150_A_ews_q0.0_k0.0.csv") ## read the 150 replicas of pre-transition time series data generated to calculate EWS

cl<- makeCluster(10) # make cluster for parallel computing
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X # gives 150 tau values for SD
stopCluster(cl)
tau1=c(X) # vector containing 150 tau values
############################for q=0.225 ##############################################
dat=vroom("lake150_A_ews_q0.225_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau2=c(X)
################################for q=0.45##########################################
dat=vroom("lake150_A_ews_q0.45_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau3=c(X)

###################################for q=0.675##########################################
dat=vroom("lake150_A_ews_q0.675_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau4=c(X)

####################################for q=0.9############################################
dat=vroom("lake150_A_ews_q0.9_k0.0.csv")
cl<- makeCluster(10)
registerDoParallel(cl)
X=foreach(jj=1:15,.combine = 'cbind')%dopar% {
  res=apply(dat[,((jj-1)*10+1):(jj*10)], 2,FUN=K_tauf,indicator = in1)
}
X
stopCluster(cl)
tau5=c(X)

## Combine the tau values we get for each species response correlation (q) value
tau=cbind(tau1,tau2,tau3,tau4,tau5)
colnames(tau)=c("0.0","0.225","0.45","0.675","0.9")
tau=data.frame(tau)
write.csv(tau,"lake150_A_ktau_SD_k0.0.csv") ## saved the tau values for SD as csv file and will be use to box plot for each q

#Using this code, one can easily compute Kendall’s tau values for different models. An example CSV file containing pre-transition timeseries
# data for each model is provided.
#These time series data can be used to recreate the Kendall’s tau values and generate the corresponding figures illustrating
# EWS strengths.